// Streeter — Material 3 Expressive design tokens
// Seed: #2B5F4B (deep blue-green forest) with olive-sage accents.
// Derived via M3 HCT tonal palettes (approximated in oklch).

const STREETER_TOKENS = {
  light: {
    // Primary — forest blue-green
    primary:            '#1F6E58',
    onPrimary:          '#FFFFFF',
    primaryContainer:   '#A6F2D6',
    onPrimaryContainer: '#00210F',
    // Secondary — sage
    secondary:          '#4E6358',
    onSecondary:        '#FFFFFF',
    secondaryContainer: '#D1E8D9',
    onSecondaryContainer:'#0B1F14',
    // Tertiary — warm olive/amber for map preview + processing
    tertiary:           '#7A5D1C',
    onTertiary:         '#FFFFFF',
    tertiaryContainer:  '#FFDF9F',
    onTertiaryContainer:'#271900',
    // Error
    error:              '#B3261E',
    onError:            '#FFFFFF',
    errorContainer:     '#F9DEDC',
    onErrorContainer:   '#410E0B',
    // Surfaces (M3 Expressive surface tones)
    background:         '#F4FBF6',
    onBackground:       '#161D19',
    surface:            '#F4FBF6',
    surfaceDim:         '#D4DBD7',
    surfaceBright:      '#F4FBF6',
    surfaceContainerLowest: '#FFFFFF',
    surfaceContainerLow:'#EFF5F0',
    surfaceContainer:   '#E9EFEB',
    surfaceContainerHigh:'#E3EAE5',
    surfaceContainerHighest:'#DEE4E0',
    onSurface:          '#161D19',
    onSurfaceVariant:   '#3F4945',
    outline:            '#6F7974',
    outlineVariant:     '#BEC9C3',
    scrim:              '#000000',
    // Hardcoded
    routeBlue:          '#3B82F6',
    previewOrange:      '#F59E0B',
    pinStart:           '#4CAF50',
    pinEnd:             '#F44336',
    // Map
    mapLand:            '#EDEFE8',
    mapRoad:            '#FFFFFF',
    mapRoadMinor:       '#F4F3EC',
    mapPark:            '#D8E6D4',
    mapWater:           '#C8DEE3',
    mapLabel:           '#7A8078',
  },
  dark: {
    primary:            '#8BD5B9',
    onPrimary:          '#00382A',
    primaryContainer:   '#00513E',
    onPrimaryContainer: '#A6F2D6',
    secondary:          '#B5CCBE',
    onSecondary:        '#21352A',
    secondaryContainer: '#374B40',
    onSecondaryContainer:'#D1E8D9',
    tertiary:           '#F5C06F',
    onTertiary:         '#422C00',
    tertiaryContainer:  '#5E4100',
    onTertiaryContainer:'#FFDF9F',
    error:              '#F2B8B5',
    onError:            '#601410',
    errorContainer:     '#8C1D18',
    onErrorContainer:   '#F9DEDC',
    background:         '#0E1512',
    onBackground:       '#DEE4E0',
    surface:            '#0E1512',
    surfaceDim:         '#0E1512',
    surfaceBright:      '#343A37',
    surfaceContainerLowest: '#08100D',
    surfaceContainerLow:'#161D19',
    surfaceContainer:   '#1A211D',
    surfaceContainerHigh:'#242B28',
    surfaceContainerHighest:'#2F3633',
    onSurface:          '#DEE4E0',
    onSurfaceVariant:   '#BEC9C3',
    outline:            '#89938D',
    outlineVariant:     '#3F4945',
    scrim:              '#000000',
    routeBlue:          '#60A5FA',
    previewOrange:      '#FBBF24',
    pinStart:           '#66BB6A',
    pinEnd:             '#EF5350',
    mapLand:            '#1B211E',
    mapRoad:            '#2E3833',
    mapRoadMinor:       '#252D29',
    mapPark:            '#1F2E24',
    mapWater:           '#1B2E35',
    mapLabel:           '#6B756F',
  },
};

window.STREETER_TOKENS = STREETER_TOKENS;
